name: ci

on:
  pull_request:
  push:
    branches: main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pdftotext
        uses: daaku/gh-action-apt-install@v4
        with:
          packages: build-essential libpoppler-cpp-dev pkg-config

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        run: uv python install

      - name: Install StatementSensei dependencies
        run: |
          uv venv
          uv pip install .

      - name: Run CI
        run: |
          uv run pytest .
          uv run flake8 webapp
